<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<!-- 强制复制所有 NuGet DLL 到输出目录 -->
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<AssemblyName>CsAC_Client</AssemblyName>
		<RootNamespace>CsAC_Client</RootNamespace>
		<ApplicationIcon>icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="icon.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
		<!-- 如果你装了 System.Drawing.Common，保留 -->
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Settings.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Settings.settings</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>
	

</Project>
